dependencies:
  override:
    - yarn add ava tap-xunit --dev # or you could use npm
test:
  override:
    - mkdir -p $CIRCLE_TEST_REPORTS/reports
    - ava --tap | tap-xunit > $CIRCLE_TEST_REPORTS/reports/ava.xml